name: gala-docs

dependencies:
  - python>=3.7
  - gsl
  - pip
  - pip:
    - -r requirements.txt
    - sphinx_astropy
    - nbsphinx
    - tqdm
    - IPython
    - jupyter
    - notebook
    - ipykernel
